### ISSUE TITLE
scss file doesn't work on ssr

### ISSUE THREAD

**Issue by vitaliemiron** [nirazanbasnet/nextjs-tailwindcss-sass-boilerplate#2]
Any change to scss file doesn't work in ssr.

<img width="1511" alt="Screen Shot 2020-03-26 at 13 30 41" src="https://user-images.githubusercontent.com/45145592/77642226-fe79da00-6f65-11ea-8d01-bc73fea19198.png">
<img width="845" alt="Screen Shot 2020-03-26 at 13 30 56" src="https://user-images.githubusercontent.com/45145592/77642251-09346f00-6f66-11ea-9ad5-d7c57eef2fec.png">

**Comment by nirazanbasnet** [comment]
Now the nextjs version is updated so all the issues has been solved.
