### ISSUE TITLE
@zeit/next-sass is Deprecated

### ISSUE THREAD

**Issue by Magimart** [nirazanbasnet/nextjs-tailwindcss-sass-boilerplate#7]
You should update your @zeit/next-sass  library as it is deprecated . More so, Next.js now has built-in support for Sass: you may want to refer to this article https://nextjs.org/docs/basic-features/built-in-css-support\#sass-support. 

So this way of using sass and tailwind in Nextjs just creates endless vacuums for bugs and with very bad performance ranking.

**Comment by nirazanbasnet** [comment]
I had updated the nextjs and other plugins so now this repo is fu;;y functional.
